using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TMI_Project
{
    public class EscalasMusicales
    {
        private static readonly string C = "C";
        private static readonly string C_ = "C#";
        private static readonly string D = "D";
        private static readonly string D_ = "D#";
        private static readonly string E = "E";
        private static readonly string F = "F";
        private static readonly string F_ = "F#";
        private static readonly string G = "G";
        private static readonly string G_ = "G#";
        private static readonly string A = "A";
        private static readonly string A_ = "A#";
        private static readonly string B = "B";
        public readonly string[] CMajor = { C, D, E, F, G, A, B };
        public readonly string[] C_Major = { C_, D_, F, F_, G_, A_, C };
        public readonly string[] DMajor = { D, E, F_, G, A, B, C_ };
        public readonly string[] D_Major = { D_, F, G, G_, A_, C, D };
        public readonly string[] EMajor = { E, F_, G_, A, B, C_, D_ };
        public readonly string[] FMajor = { F, G, A, A_, C, D, E };
        public readonly string[] F_Major = { F_, G_, A_, B, C_, D_, F };
        public readonly string[] GMajor = { G, A, B, C, D, E, F_ };
        public readonly string[] G_Major = { G_, A_, C, C_, D_, F, G };
        public readonly string[] AMajor = { A, B, C_, D, E, F_, G_ };
        public readonly string[] A_Major = { A, B, C_, D, E, F_, G_ };
        public readonly string[] BMajor = { B, C_, D_, E, F_, G_, A_ };
        public readonly string[] CMinor = { C, D, D_, F, G, G_, A_ };
        public readonly string[] C_Minor = { C_, D_, E, F_, G_, A, B };
        public readonly string[] DMinor = { D, E, F, G, A, A_, C };
        public readonly string[] D_Minor = { D_, F, F_, G_, A_, B, C_ };
        public readonly string[] EMinor = { E, F_, G, A, B, C, D };
        public readonly string[] FMinor = { F, G, G_, A_, C, C_, D_ };
        public readonly string[] F_Minor = { F_, G_, A, B, C_, D, E };
        public readonly string[] GMinor = { G, A, A_, C, D, D_, F };
        public readonly string[] G_Minor = { G_, A_, B, C_, D_, E, F_ };
        public readonly string[] AMinor = { A, B, C, D, E, F, G };
        public readonly string[] A_Minor = { A_, C, C_, D_, F, F_, G_ };
        public readonly string[] BMinor = { B, C_, D, E, F_, G, A };
        public readonly string[] CDorian = { C, D, D_, F, G, A, A_ };
        public readonly string[] CPhrygian = { C, C_, D_, F, G, G_, A_ };
        public readonly string[] CLydian = { D, F, E, F_, G, A, B };
        public readonly string[] CMixolydian = { C, D, E, F, G, A, A_ };
        public readonly string[] CLocrian = { C, C_, D_, F, F_, G_, A_ };
        public readonly string[] C_Dorian = { C_, D_, E, F_, G_, A_, B };
        public readonly string[] C_Phrygian = { C_, D, E, F_, G_, A, B };
        public readonly string[] C_Lydian = { C_, D_, F, G, G_, A_, C };
        public readonly string[] C_Mixolydian = { C_, D_, F, F_, G_, A_, B };
        public readonly string[] C_Locrian = { C_, D, E, F_, G, A, B };
        public readonly string[] DDorian = { D, E, F, G, A, B, C };
        public readonly string[] DPhrygian = { D, D_, F, G, A, A_, C };
        public readonly string[] DLydian = { D, E, F_, G_, A, B, C_ };
        public readonly string[] DMixolydian = { D, E, F_, G, A, B, C };
        public readonly string[] DLocrian = { D, D_, F, G, G_, A_, C };
        public readonly string[] D_Dorian = { D_, F, F_, G_, A_, C, C_ };
        public readonly string[] D_Phrygian = { D_, E, F_, G_, A_, B, C_ };
        public readonly string[] D_Lydian = { D_, F, G, A, A_, C, D };
        public readonly string[] D_Mixolydian = { D_, F, G, G_, A_, C, C_ };
        public readonly string[] D_Locrian = { D_, E, F_, G_, A, B, C_ };
        public readonly string[] EDorian = { E, F_, G, A, B, C_, D };
        public readonly string[] EPhrygian = { E, F, G, A, B, C, D };
        public readonly string[] ELydian = { E, F_ ,G_, A_, B, C_, D_ };
        public readonly string[] EMixolydian = { E, F_, G_, A, B, C_, D };
        public readonly string[] ELocrian = { E, F, G, A, A_, C, D };
        public readonly string[] FDorian = { F, G, G_, A_, C, D, D_ };
        public readonly string[] FPhrygian = { F, F_, G_, A_, C, C_, D_ };
        public readonly string[] FLydian = { F, G, A, B, C, D, E };
        public readonly string[] FMixolydian = { F, G, A, A_, C, D, D_ };
        public readonly string[] FLocrian = { F, F_, G_, A_, B, C_, D_ };
        public readonly string[] F_Dorian = { F_, G_, A, B, C_, D_, E };
        public readonly string[] F_Phrygian = { F_, G, A, B, C_, D, E };
        public readonly string[] F_Lydian = { F_, G_, A_, C, C_, D_, F };
        public readonly string[] F_Mixolydian = { F_, G_, A_, B, C_, D_, E };
        public readonly string[] F_Locrian = { F_, G, A, B, C, D, E };
        public readonly string[] GDorian = { G, A, A_, C, D, E, F };
        public readonly string[] GPhrygian = { G, G_, A_, C, D, D_, F };
        public readonly string[] GLydian = { G, A, B, C_, D, E, F_ };
        public readonly string[] GMixolydian = { G, A, B, C, D, E, F };
        public readonly string[] GLocrian = { G, G_, A_, C, C_, D_, F };
        public readonly string[] G_Dorian = { G_, A_, B, C_, D_, F, F_ };
        public readonly string[] G_Phrygian = { G_, A, B, C_, D_, E, F_ };
        public readonly string[] G_Lydian = { G_, A_, C, D, D_, F, G };
        public readonly string[] G_Mixolydian = { G_, A_, C, C_, D_, F, F_ };
        public readonly string[] G_Locrian = { G_, A, B, C_, D, E, F_ };
        public readonly string[] ADorian = { A, B, C, D, E, F_, G };
        public readonly string[] APhrygian = { A, A_, C, D, E, F, G };
        public readonly string[] ALydian = { A, B, C_, D_, E, F_, G_ };
        public readonly string[] AMixolydian = { A, B, C_, D, E, F_, G };
        public readonly string[] ALocrian = { A, A_, C, D, D_, F, G };
        public readonly string[] A_Dorian = { A_, C, C_, D_, F, G, G_ };
        public readonly string[] A_Phrygian = { A_, B, C_, D_, F, F_, G_ };
        public readonly string[] A_Lydian = { A_, C, D, E, F, G, A };
        public readonly string[] A_Mixolydian = { A_, C, D, D_, F, G, G_ };
        public readonly string[] A_Locrian = { A_, B, C_, D_, E, F_, G_ };
        public readonly string[] BDorian = { B, C_, D, E, F_, G_, A };
        public readonly string[] BPhrygian = { B, C, D, E, F_, G, A };
        public readonly string[] BLydian = { B, C_, D_, F, F_, G_, A_ };
        public readonly string[] BMixolydian = { B, C_, D_, E, F_, G_, A };
        public readonly string[] BLocrian = { B, C, D, E, F, G, A };

        public readonly List<string[]> escalas = null;

        public EscalasMusicales()
        {
            escalas = new List<string[]>();
            escalas.Add(CMajor);
            escalas.Add(CMinor);
            escalas.Add(C_Major);
            escalas.Add(C_Minor);
            escalas.Add(DMajor);
            escalas.Add(DMinor);
            escalas.Add(D_Major);
            escalas.Add(D_Minor);
            escalas.Add(EMajor);
            escalas.Add(EMinor);
            escalas.Add(FMajor);
            escalas.Add(FMinor);
            escalas.Add(F_Major);
            escalas.Add(F_Minor);
            escalas.Add(GMajor);
            escalas.Add(GMinor);
            escalas.Add(G_Major);
            escalas.Add(G_Minor);
            escalas.Add(AMajor);
            escalas.Add(AMinor);
            escalas.Add(A_Major);
            escalas.Add(A_Minor);
            escalas.Add(BMajor);
            escalas.Add(CDorian);
            escalas.Add(C_Dorian);
            escalas.Add(DDorian);
            escalas.Add(D_Dorian);
            escalas.Add(EDorian);
            escalas.Add(FDorian);
            escalas.Add(F_Dorian);
            escalas.Add(GDorian);
            escalas.Add(G_Dorian);
            escalas.Add(ADorian);
            escalas.Add(A_Dorian);
            escalas.Add(BDorian);
            escalas.Add(CPhrygian);
            escalas.Add(C_Phrygian);
            escalas.Add(DPhrygian);
            escalas.Add(D_Phrygian);
            escalas.Add(EPhrygian);
            escalas.Add(FPhrygian);
            escalas.Add(F_Phrygian);
            escalas.Add(GPhrygian);
            escalas.Add(G_Phrygian);
            escalas.Add(APhrygian);
            escalas.Add(A_Phrygian);
            escalas.Add(BPhrygian);
            escalas.Add(CLydian);
            escalas.Add(C_Lydian);
            escalas.Add(DLydian);
            escalas.Add(D_Lydian);
            escalas.Add(ELydian);
            escalas.Add(FLydian);
            escalas.Add(F_Lydian);
            escalas.Add(GLydian);
            escalas.Add(G_Lydian);
            escalas.Add(ALydian);
            escalas.Add(A_Lydian);
            escalas.Add(BLydian);
            escalas.Add(CMixolydian);
            escalas.Add(C_Mixolydian);
            escalas.Add(DMixolydian);
            escalas.Add(D_Mixolydian);
            escalas.Add(EMixolydian);
            escalas.Add(FMixolydian);
            escalas.Add(F_Mixolydian);
            escalas.Add(GMixolydian);
            escalas.Add(G_Mixolydian);
            escalas.Add(AMixolydian);
            escalas.Add(A_Mixolydian);
            escalas.Add(BMixolydian);
            escalas.Add(CLocrian);
            escalas.Add(C_Locrian);
            escalas.Add(DLocrian);
            escalas.Add(D_Locrian);
            escalas.Add(ELocrian);
            escalas.Add(FLocrian);
            escalas.Add(F_Locrian);
            escalas.Add(GLocrian);
            escalas.Add(G_Locrian);
            escalas.Add(ALocrian);
            escalas.Add(A_Locrian);
            escalas.Add(BLocrian);
        }

    }
}
